### ISSUE TITLE
F24: missing module while running fedmsg-notify-config

### ISSUE THREAD

**Issue by ashcrow** [fedora-infra/fedmsg-notify#28]
```
$ rpm -q fedmsg-notify
fedmsg-notify-0.5.5-4.fc24.noarch
```

When trying to run ``fedmsg-notify-config` the following error occurs:

```
$ fedmsg-notify-config 
/usr/lib/python2.7/site-packages/fedmsg_notify/gui.py:26: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gtk, Gio
No module named problem
Traceback (most recent call last):
  File "/usr/bin/fedmsg-notify-config", line 9, in <module>
    load_entry_point('fedmsg-notify==0.5.5', 'console_scripts', 'fedmsg-notify-config')()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 547, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2720, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2380, in load
    return self.resolve()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2386, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python2.7/site-packages/fedmsg_notify/gui.py", line 28, in <module>
    from .filters import filters, get_enabled_filters
  File "/usr/lib/python2.7/site-packages/fedmsg_notify/filters.py", line 24, in <module>
    from .distro_specific import (get_installed_packages,
ImportError: cannot import name get_reported_bugs
```

A similar error occurs with `fedmsg-notify-daemon`

```
$ fedmsg-notify-daemon --help
/usr/lib64/python2.7/site-packages/twisted/internet/gireactor.py:115: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gtk as _gtk
No handlers could be found for logger "moksha.hub"
/usr/lib/python2.7/site-packages/fedmsg_notify/daemon.py:43: PyGIWarning: Notify was imported without specifying a version first. Use gi.require_version('Notify', '0.7') before import to ensure that the right version gets loaded.
  from gi.repository import Notify, Gio, GLib
No module named problem
Traceback (most recent call last):
  File "/usr/bin/fedmsg-notify-daemon", line 9, in <module>
    load_entry_point('fedmsg-notify==0.5.5', 'console_scripts', 'fedmsg-notify-daemon')()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 547, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2720, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2380, in load
    return self.resolve()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2386, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python2.7/site-packages/fedmsg_notify/daemon.py", line 45, in <module>
    from filters import get_enabled_filters, filters as all_filters
  File "/usr/lib/python2.7/site-packages/fedmsg_notify/filters.py", line 24, in <module>
    from .distro_specific import (get_installed_packages,
ImportError: cannot import name get_reported_bugs
```

It looks like the root of the issue is a missing module named `problem` in [_fedora.py](https://github.com/fedora-infra/fedmsg-notify/blob/develop/fedmsg_notify/distro_specific/_fedora.py#L22). I looked briefly to see if I could find the package that provides `problem` but wasn't able to locate it.

**Comment by abompard** [comment]
The `problems` module is provided by the ABRT python bindings. Unfortunately those aren't available on PyPI, so we can't add them as dependencies in the `setup.py` file.

The spec files needs to be fixed though, to add a dependency on the `abrt-python` package. I just did that, and will push the update to the stable releases.
